Issue while parsing: <class 'genie.libs.parser.iosxe.show_platform.ShowRedundancy'>

Traceback (most recent call last):
  File "src/genie/cli/commands/learn.py", line 365, in genie.cli.commands.learn.LearnCommand._retrieve_ops
  File "/home/ipvzero/Nornir/pyATS-Network-Testing/lib/python3.10/site-packages/genie/libs/ops/platform/iosxe/platform.py", line 328, in learn
    self.make(final_call=True)
  File "/home/ipvzero/Nornir/pyATS-Network-Testing/lib/python3.10/site-packages/genie/ops/base/base.py", line 103, in make
    self.maker.make(*args, **kwargs)
  File "src/genie/ops/base/maker.py", line 315, in genie.ops.base.maker.Maker.make
  File "src/genie/ops/base/maker.py", line 427, in genie.ops.base.maker.Maker._call_parser
  File "src/genie/metaparser/_metaparser.py", line 342, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 322, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 419, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['red_sys_info', 'oper_red_mode'], ['red_sys_info', 'conf_red_mode']]
